<dl class="inews_com">
          <dt><a href="field:arcurl /]" target="_blank"><img src="[field:picname/]" /></a></dt>
          <dd><strong><a href="field:arcurl /]" title="[field:title /]" target="_blank">[field:title /]</a></strong><span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span>
            <p>[field:infos/]...</p>
            <a href="field:arcurl /]" class="a" target="_blank">查看详情 &gt;&gt;</a></dd>
        </dl>