<?php
$z[0]=Array("field","",171,190);
$z[0][4]['name']="title";
$z[1]=Array("global","",191,217);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",998,1033);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",1508,1691);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<a href='~typelink~' class='title_menu_over'>~typename~</a>";
$z[4]=Array("field","",1795,1816);
$z[4][4]['name']="content";
$z[5]=Array("include","",1848,1885);
$z[5][4]['filename']="footer.htm";

?>