<?php
$z[0]=Array("field","",171,190);
$z[0][4]['name']="title";
$z[1]=Array("global","",191,217);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",829,864);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",1339,1522);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<a href='~typelink~' class='title_menu_over'>~typename~</a>";
$z[4]=Array("field","",1681,1708);
$z[4][4]['name']="litpic";
$z[5]=Array("field","",1821,1840);
$z[5][4]['name']="title";
$z[6]=Array("field","",1884,1903);
$z[6][4]['name']="jiage";
$z[7]=Array("field","",1954,1976);
$z[7][4]['name']="gongneng";
$z[8]=Array("field","",2009,2028);
$z[8][4]['name']="guige";
$z[9]=Array("field","",2061,2080);
$z[9][4]['name']="gaodu";
$z[10]=Array("field","",2113,2132);
$z[10][4]['name']="yanse";
$z[11]=Array("field","",2364,2382);
$z[11][4]['name']="body";
$z[12]=Array("prenext","",2472,2497);
$z[12][4]['get']="pre";
$z[13]=Array("prenext","",2541,2567);
$z[13][4]['get']="next";
$z[14]=Array("include","",2655,2692);
$z[14][4]['filename']="footer.htm";

?>