<?php
$z[0]=Array("field","",171,190);
$z[0][4]['name']="title";
$z[1]=Array("global","",191,217);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",829,864);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",1335,1518);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<a href='~typelink~' class='title_menu_over'>~typename~</a>";
$z[4]=Array("field","",1593,1612);
$z[4][4]['name']="title";
$z[5]=Array("field","",1656,1708);
$z[5][4]['name']="pubdate";
$z[5][4]['function']="MyDate('Y-m-d',@me)";
$z[6]=Array("field","",1810,1828);
$z[6][4]['name']="body";
$z[7]=Array("prenext","",1918,1943);
$z[7][4]['get']="pre";
$z[8]=Array("prenext","",1987,2013);
$z[8][4]['get']="next";
$z[9]=Array("include","",2098,2135);
$z[9][4]['filename']="footer.htm";

?>