
<field:ndxm itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ndxm>

<field:nddh itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:nddh>

<field:ndyx itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ndyx>

<field:ndqq itemname="QQ" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:ndqq>

<field:ndnr itemname="内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:ndnr>
