<?php
$z[0]=Array("field","",171,190);
$z[0][4]['name']="title";
$z[1]=Array("global","",191,217);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",613,648);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",1123,1306);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<a href='~typelink~' class='title_menu_over'>~typename~</a>";
$z[4]=Array("list","\r\n		<dl>\r\n          <dt><img src=\"[field:picname/]\" /><a href=\"[field:arcurl/]\" title=\"[field:title/]\"></a></dt>\r\n          <dd><a href=\"[field:arcurl/]\">[field:title/]</a></dd>\r\n        </dl>\r\n		",1438,1670);
$z[4][4]['pagesize']="9";
$z[5]=Array("pagelist","",1791,1853);
$z[5][4]['listitem']="index,pre,next,pageno";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1925,1962);
$z[6][4]['filename']="footer.htm";

?>