<?php
$z[0]=Array("field","",171,190);
$z[0][4]['name']="title";
$z[1]=Array("global","",191,217);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",613,648);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",1119,1302);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<a href='~typelink~' class='title_menu_over'>~typename~</a>";
$z[4]=Array("list","\r\n	  <dl>\r\n        <dt><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" /></a></dt>\r\n        <dd><strong><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></strong><span>2015-09-04</span>\r\n          <p>[field:infos/]...</p>\r\n        </dd>\r\n      </dl>\r\n	  ",1380,1708);
$z[4][4]['pagesize']="5";
$z[4][4]['infolen']="400";
$z[5]=Array("pagelist","",1808,1870);
$z[5][4]['listitem']="index,pre,next,pageno";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",1916,1953);
$z[6][4]['filename']="footer.htm";

?>