<?php
$z[0]=Array("field","",171,190);
$z[0][4]['name']="title";
$z[1]=Array("global","",191,217);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",785,820);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel"," <a href=\"[field:typeurl/]\">[field:typename/]</a> ",1294,1477);
$z[3][4]['row']="10";
$z[3][4]['type']="son";
$z[3][4]['col']="1";
$z[3][4]['currentstyle']="<a href='~typelink~' class='title_menu_over'>~typename~</a>";
$z[4]=Array("list","\r\n		<dl>\r\n          <dt><a href=\"[field:picname/]\" rel=\"lightbox[roadtrip]\" title=\"[field:title/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" /></a></dt>\r\n          <dd><a href=\"[field:picname/]\" title=\"\" target=\"_blank\">[field:title/]</a></dd>\r\n        </dl>\r\n		",1598,1917);
$z[4][4]['pagesize']="5";
$z[4][4]['infolen']="400";
$z[5]=Array("pagelist","",2038,2100);
$z[5][4]['listitem']="index,pre,next,pageno";
$z[5][4]['listsize']="5";
$z[6]=Array("include","",2172,2209);
$z[6][4]['filename']="footer.htm";

?>